AWSTemplateFormatVersion: '2010-09-09'
Description: Security Groups

Resources:

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB Security Group
      GroupName: SecurityGroups-Julian-Vergel-ALB
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Security Group
      GroupName: SecurityGroups-Julian-Vergel-EC2

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSecurityGroup

        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:

  ALBSG:
    Value: !Ref ALBSecurityGroup
    Export:
      Name: ALBSG

  EC2SG:
    Value: !Ref EC2SecurityGroup
    Export:
      Name: EC2SG