name: Deploy

on:
  workflow_dispatch:

jobs:

  Deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Deploy Security
        run: |
          aws cloudformation deploy \
            --stack-name Security-Julian-JuanJose \
            --template-file cloudformation/security.yml

      - name: Deploy EC2
        run: |
          aws cloudformation deploy \
            --stack-name EC2-Julian-JuanJose \
            --template-file cloudformation/ec2.yml \
            --parameter-overrides KeyPair=${{ secrets.KEYPAIR_NAME }}

      - name: Deploy ALB-ASG
        run: |
          aws cloudformation deploy \
            --stack-name ALB-ASG-Julian-JuanJose \
            --template-file cloudformation/alb-asg.yml \
            --parameter-overrides \
            VpcId=vpc-058906242a9188962 \
            PublicSubnet1=subnet-0c976733d21144853 \
            PublicSubnet2=subnet-0db3197e6eae4c03d

      - name: Get ASG Name
        run: |
          ASG_NAME=$(aws cloudformation describe-stacks \
            --stack-name ALB-ASG-Julian-JuanJose \
            --query "Stacks[0].Outputs[?OutputKey=='ASGName'].OutputValue" \
            --output text)

          echo "ASG_NAME=$ASG_NAME" >> $GITHUB_ENV

      - name: Deploy Automation
        run: |
          aws cloudformation deploy \
            --stack-name Automation-Julian-JuanJose \
            --template-file cloudformation/automation.yml \
            --parameter-overrides \
            AutoScalingGroupName=$ASG_NAME